# Configuration file for MacsLibs
# Library made by Macs @ MacsWorks.eu
# Copyrighted by MacsWorks. Do not redistribute!

lang:
  no-permission: "&c[&4!&c] You don't have permission!"
  usage-header: "&7Usage for &b/%command%&7:"
  usage-subcommand: "&b/%command% %subcommand%%args%: &f%use%"

#Set this to false if you don't wish to receive promotional messages from MacsWorks
advertising: true